package env

const TOKEN_KEY = "SLACK_TOKEN"
const ACTIONS_PORT_KEY = "ACTIONS_PORT"
const POSTCODE = "POSTCODE"
const STILL_WATER_LINK = "STILL_WATER_LINK"
const SPARKLING_WATER_LINK = "SPARKLING_WATER_LINK"
