package env

const TOKEN_KEY = "SLACK_TOKEN"
const ACTIONS_PORT_KEY = "ACTIONS_PORT"
const POSTCODE_KEY = "POSTCODE"
const STILL_WATER_ID_KEY = "STILL_WATER_ID"
const SPARKLING_WATER_ID_KEY = "SPARKLING_WATER_ID"
const EMAIL_KEY = "EMAIL"
const PASSWORD_KEY = "PASSWORD"
